name: Test and Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache node modules
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build project
      # if: success()  # Only run build if tests pass
      run: npm run build

    - name: Commit and push dist folder
      run: |
        # Configure Git user
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Copy the generated `dist` folder to the root of the repository
        cp -r dist/* .

        # Add, commit, and push the updated `dist` folder
        git add dist
        git commit -m "Update dist folder from GitHub Actions"
        git push -f origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
