name: Test and Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache node modules
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node_modules_cache

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build project
      if: success()  # Only run build if tests pass
      run: npm run build

    - name: Deploy (if necessary)
      run: |
        # Add your deployment steps here
        echo "Deploying to production..."
